### ISSUE TITLE
Where i can find my muse address device?

### ISSUE THREAD

**Issue by LiemFrans** [mharthoorn/Muse.Net#1]

**Comment by mharthoorn** [comment]
Just updated the Muse.Console application. It requires .NET framework 4.7.2 at the moment.
You can use the console app with the ```scan``` command to discover your muse Bluetooth address.

In your project folder command line
```
> dotnet run scan
```
Might take a few seconds

**Comment by mharthoorn** [comment]
Alternatively in Windows, after you paired your device with the Bluetooth Device Settings window, you can find the device details under "Devices and Printers". That also shows you the address.

**Comment by LiemFrans** [comment]
![image](https://user-images.githubusercontent.com/41262407/45084449-8dc36080-b128-11e8-884c-a241136cb512.png)

wheres my address, sorry for my bad english.. :")

**Comment by mharthoorn** [comment]
The number behind the model 0055dab084f8 is your mac addres (hexadecimal). 
In C# that will be ```0x0055dab084f8```.

**Comment by LiemFrans** [comment]
okey, i got it, 
now i run the livefeed, but the graph is constantly straight , 
![image](https://user-images.githubusercontent.com/41262407/45085302-8bfa9c80-b12a-11e8-9ecc-46cb59a9470a.png)

**Comment by mharthoorn** [comment]
I am still working on the Live Feed App. I need a few days to get the right output there. I will give you an update when it works for me. -)

**Comment by LiemFrans** [comment]
woaa, thankyou sir .... 👍

**Comment by mharthoorn** [comment]
The graphical output should work now. I will work on better performance at a later time.
Let me know if it works.
