### ISSUE TITLE
Meaning of values

### ISSUE THREAD

**Issue by NickDevoctomy** [mharthoorn/Muse.Net#5]
Hi @mharthoorn , great sample, thankyou very much! This is perfect considering muse have pulled their SDK.

Anyway, I have a quick question, do you have any reference material saying what the values actually mean?  At a minimum, what does each channel signify?

                    Channel.EEG_AF7,
                    Channel.EEG_AF8,
                    Channel.EEG_TP10,
                    Channel.EEG_TP9,
                    Channel.EEG_AUX

Many thanks in advance.

**Comment by mharthoorn** [comment]
These are the 5 actual brain-wave signal channels. As far as I understood the _AUX is only for calibration, so basically the AF7, AF8, TP9, TP10 are the 4 channels to use. 

The channels are named after the 10-20 standard for electrode placement.
https://en.wikipedia.org/wiki/10%E2%80%9320_system_(EEG)#Electrode_labeling

This article is a nice image of the the full location list under 
Paragraph 4.2 Data Acquisition.

**Comment by NickDevoctomy** [comment]
Sorry for the delay in getting back to you. Thanks for the information!
